stages:
  - build
  - deploy

variables:
  RELEASE_ID: $CI_PROJECT_NAME@$CI_COMMIT_SHORT_SHA

kaniko-build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  variables:
    DOCKERFILE: $CI_PROJECT_DIR/Dockerfile
    CONTAINER_IMAGE: $DOCKER_REGISTRY/kszk-hat/$CI_PROJECT_NAME
  script:
    - echo "{\"auths\":{\"$DOCKER_REGISTRY\":{\"username\":\"$REGISTRY_USER\",\"password\":\"$REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $DOCKERFILE --target app --destination $CONTAINER_IMAGE-app:$CI_COMMIT_TAG
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $DOCKERFILE --target updater --destination $CONTAINER_IMAGE-updater:$CI_COMMIT_TAG
  when: manual

helm-deploy:
  stage: deploy
  image: harbor.sch.bme.hu/proxy-docker.io/dtzar/helm-kubectl:4.2.3
  before_script:
    - chmod 600 $KUBECONFIG
    - helm registry login --username=$REGISTRY_USER --password=$REGISTRY_PASSWORD $DOCKER_REGISTRY
  script:
    - helm upgrade $CI_PROJECT_NAME helm --install --atomic -f helm/values.yaml --namespace kszk-bmemap --set image.tag=$CI_COMMIT_SHA
  needs: ['kaniko-build']
  tags: [k9r]