apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.app.name }}:{{ default "latest" .Values.image.app.tag }}
          resources:
            requests:
              memory: "20Mi"
              cpu: "50m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: "/usr/share/nginx/html/data"
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
